"""Step 2 of the Frenetix parameter sweep (run in `frenetix-cosim` env).

Reads the CommonRoad XMLs generated by generate_sweep_scenarios.py and runs a
full Frenetix co-simulation for each combination, scoring the ego trajectory and
writing a CSV summary.

PARAM_GRID must be kept in sync with generate_sweep_scenarios.py (step 1).

Usage:
    # Step 1 (once, or whenever the xosc changes):
    conda run -n cr-osc-converter python generate_sweep_scenarios.py

    # Step 2:
    conda run -n frenetix-cosim python scenario_sweep.py
    conda run -n frenetix-cosim python scenario_sweep.py \\
        --xosc ../esmini/resources/xosc/keep_lateral_distance_external.xosc \\
        --scenarios sweep_scenarios/ --desired-velocity 8.0 --output sweep_results/
"""

import argparse
import csv
import os
import re
import sys
import tempfile
from itertools import product

import numpy as np

THIS_DIR = os.path.dirname(os.path.realpath(__file__))

from osc2cr_extended import paths

from osc2cr_extended.cosim.frenetix.cosimulation import CoSimulation

DEFAULT_XOSC = str(paths.ESMINI_XOSC / "keep_lateral_distance_external.xosc")
DEFAULT_SCENARIOS = str(paths.OUTPUT_DIR / "sweep_scenarios")
DEFAULT_OUTPUT    = str(paths.OUTPUT_DIR / "sweep_results")

PARAM_GRID = {
    "EgoSpeed":  [72, 90, 108],
    "EgoStartS": [30, 50, 70],
}


def apply_params(xosc_path: str, params: dict) -> str:
    with open(xosc_path, "r", encoding="utf-8") as f:
        text = f.read()
    for name, value in params.items():
        text = re.sub(
            r'(name="' + re.escape(name) + r'"[^/\n]*?)value="[^"]*"',
            r'\g<1>value="' + str(value) + '"',
            text,
        )
    xosc_dir = os.path.dirname(os.path.abspath(xosc_path))
    tmp = tempfile.NamedTemporaryFile(
        suffix=".xosc", delete=False, mode="w", encoding="utf-8", dir=xosc_dir
    )
    tmp.write(text)
    tmp.close()
    return tmp.name


def params_slug(params: dict) -> str:
    return "_".join(f"{k}{v}" for k, v in params.items())


def score_result(result, planning_problem, dt: float) -> dict:
    states = result.ego_trajectory.state_list
    n = len(states)

    goal_reached = int(planning_problem.goal.is_reached(states[-1]))

    velocities = np.array([s.velocity for s in states])

    accels = np.array(
        [s.acceleration for s in states
         if hasattr(s, "acceleration") and s.acceleration is not None]
    )
    if len(accels) > 1:
        jerk = np.diff(accels) / dt
        rms_jerk = float(np.sqrt(np.mean(jerk ** 2)))
    else:
        rms_jerk = float("nan")

    if result.overtaker_states:
        pairs = min(n, len(result.overtaker_states))
        dists = [
            float(np.linalg.norm(states[i].position - result.overtaker_states[i].position))
            for i in range(pairs)
        ]
        min_dist = min(dists)
    else:
        min_dist = float("nan")

    return {
        "n_steps":               n,
        "duration_s":            round(n * dt, 2),
        "goal_reached":          goal_reached,
        "mean_velocity_ms":      round(float(np.mean(velocities)), 3),
        "rms_jerk":              round(rms_jerk, 4),
        "min_dist_to_overtaker": round(min_dist, 3),
    }


def run_sweep(xosc_path: str, scenarios_dir: str, param_grid: dict,
              desired_velocity: float, output_dir: str) -> list[dict]:
    os.makedirs(output_dir, exist_ok=True)

    keys   = list(param_grid.keys())
    combos = [dict(zip(keys, vals)) for vals in product(*param_grid.values())]
    records = []

    for i, params in enumerate(combos, 1):
        slug         = params_slug(params)
        scenario_xml = os.path.join(scenarios_dir, f"scenario_init_{slug}.xml")

        if not os.path.exists(scenario_xml):
            print(f"\n[sweep] {i}/{len(combos)}  SKIP (no scenario XML): {scenario_xml}")
            print("         Run generate_sweep_scenarios.py first.")
            continue

        print(f"\n[sweep] {i}/{len(combos)}  params={params}")
        tmp_xosc = apply_params(xosc_path, params)
        try:
            cosim = CoSimulation(
                xosc_path=tmp_xosc,
                scenario_xml=scenario_xml,
                desired_velocity=desired_velocity,
            )
            result = cosim.run()
            dt = cosim.config_plan.planning.dt
            pp = cosim.planning_problem

            out_dir = os.path.join(output_dir, slug)
            result.write_solution(output_dir=out_dir)
            result.write_combined_scenario(path=os.path.join(out_dir, "cosim_result.xml"))

            metrics = score_result(result, pp, dt)
        except Exception as exc:
            print(f"[sweep]   FAILED: {exc}")
            metrics = {
                "n_steps": -1, "duration_s": -1, "goal_reached": 0,
                "mean_velocity_ms": float("nan"),
                "rms_jerk": float("nan"),
                "min_dist_to_overtaker": float("nan"),
            }
        finally:
            os.unlink(tmp_xosc)

        record = {**params, **metrics}
        records.append(record)
        print(f"[sweep]   → {metrics}")

    if not records:
        print("[sweep] no results — did you run generate_sweep_scenarios.py first?")
        return records

    csv_path = os.path.join(output_dir, "sweep_results.csv")
    with open(csv_path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(records[0].keys()))
        writer.writeheader()
        writer.writerows(records)

    print(f"\n[sweep] {len(records)} runs written to {csv_path}")
    return records


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--xosc", default=DEFAULT_XOSC,
                        help="OpenSCENARIO file (must match what generate_sweep_scenarios.py used)")
    parser.add_argument("--scenarios", default=DEFAULT_SCENARIOS,
                        help="directory of scenario_init_*.xml files from generate_sweep_scenarios.py")
    parser.add_argument("--desired-velocity", type=float, default=8.0)
    parser.add_argument("--output", default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    run_sweep(args.xosc, args.scenarios, PARAM_GRID, args.desired_velocity, args.output)


if __name__ == "__main__":
    main()
